# Generated by Django 4.1.2 on 2022-10-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Apartments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.CharField(max_length=30)),
                ("date", models.DateField(auto_now=True)),
                ("floorplan", models.CharField(max_length=30)),
                ("available", models.IntegerField()),
                ("bedrooms", models.IntegerField()),
                ("baths", models.FloatField()),
                ("size", models.IntegerField(blank=True, null=True)),
                ("deposit", models.IntegerField(blank=True, null=True)),
                ("rent", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Apartments",
            },
        ),
    ]
