# Generated by Django 4.1.2 on 2022-10-24 04:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartments",
            name="available",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="apartments",
            name="baths",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="apartments",
            name="bedrooms",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="apartments",
            name="deposit",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="apartments",
            name="rent",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="apartments",
            name="size",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
