# Generated by Django 4.1.2 on 2022-10-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_apartments_available_alter_apartments_baths_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartments",
            name="available",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="apartments",
            name="baths",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="apartments",
            name="bedrooms",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="apartments",
            name="deposit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="apartments",
            name="floorplan",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="apartments",
            name="rent",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="apartments",
            name="size",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
