# Generated by Django 4.1.2 on 2022-10-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_apartments_available_alter_apartments_baths_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartments",
            name="date",
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
