# Generated by Django 4.1.1 on 2022-11-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0005_delete_apartments"),
    ]

    operations = [
        migrations.CreateModel(
            name="Apartments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.CharField(max_length=30)),
                ("date", models.DateField(auto_now=True, null=True)),
                ("floorplan", models.CharField(blank=True, max_length=30, null=True)),
                ("available", models.CharField(blank=True, max_length=100, null=True)),
                ("bedrooms", models.CharField(blank=True, max_length=100, null=True)),
                ("baths", models.CharField(blank=True, max_length=100, null=True)),
                ("size", models.CharField(blank=True, max_length=100, null=True)),
                ("deposit", models.CharField(blank=True, max_length=100, null=True)),
                ("rent", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name_plural": "Apartments",
            },
        ),
    ]
